# Generated by Django 4.0.5 on 2023-09-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
            ],
            options={
                'db_table': 'examination_result',
            },
        ),
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
            ],
            options={
                'db_table': 'examination_type',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除标志')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('delete_time', models.DateTimeField(null=True, verbose_name='删除时间')),
                ('examination_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examinationresult')),
                ('examination_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examinationtype')),
            ],
            options={
                'db_table': 'examination',
            },
        ),
    ]
