# Generated by Django 4.0.5 on 2023-09-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_examination_examination_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='examination_result',
        ),
        migrations.AddField(
            model_name='examination',
            name='result',
            field=models.CharField(default=1, max_length=255, verbose_name='RTL，CSA，AI'),
            preserve_default=False,
        ),
    ]
