# Generated by Django 4.0.5 on 2023-09-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_examinationtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='examination_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.examinationtype'),
            preserve_default=False,
        ),
    ]
