# Generated by Django 4.0.5 on 2023-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='input_img',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='检测图片'),
        ),
        migrations.AddField(
            model_name='examination',
            name='output_img',
            field=models.ImageField(blank=True, upload_to='outputs/', verbose_name='输出图片'),
        ),
    ]
