# Generated by Django 4.0.5 on 2023-09-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_examination_input_img_examination_output_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='input_img',
            new_name='input_image',
        ),
        migrations.RenameField(
            model_name='examination',
            old_name='output_img',
            new_name='output_image',
        ),
    ]
