# Generated by Django 4.0.5 on 2023-09-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_input_img_examination_input_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='input_image',
            field=models.ImageField(blank=True, upload_to='inputs/', verbose_name='检测图片'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11),
        ),
    ]
