# Generated by Django 4.0.5 on 2023-09-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_patient_zone_user_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='zone',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.zone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zone',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.zone'),
        ),
    ]
