# Generated by Django 4.0.5 on 2023-11-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_patient_zone_alter_user_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, default='FFewnsLVkAAg1fI.jpg', null=True, upload_to='profiles/', verbose_name='头像'),
        ),
    ]
