# Generated by Django 4.0.5 on 2023-11-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_patient_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, default='Untitled.png', null=True, upload_to='profiles/', verbose_name='头像'),
        ),
    ]
